server:
  port: 9093

spring:
  profiles:
    active:
    - ${SPRING_PROFILE}

---

spring:
  profiles: dev
  
  application:
    name: BookingService
  
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate 
    properties:
      hibernate: 
        default_schema: ${DB_SCHEMA}
      show-sql: true
      
  
---

spring:
  profiles: prod
  
  application:
    name: BookingService
  
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
      show-sql: false